version: "3.1"

services:
  keycloak:
    image: jboss/keycloak:latest
    container_name: keycloak_service
    ports:
      - 8080:8080
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - KEYCLOAK_IMPORT=/tmp/realm-export.json
    volumes:
      - ./tmp/realm-export.json:/tmp/realm-export.json